# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dylan/git/GMTK2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dylan/git/GMTK2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dylan/git/GMTK2025/CMakeFiles /home/dylan/git/GMTK2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dylan/git/GMTK2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_program

# Build rule for target.
my_program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_program
.PHONY : my_program

# fast build rule for target.
my_program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/build
.PHONY : my_program/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.s
.PHONY : main.cpp.s

src/Alien.o: src/Alien.cpp.o
.PHONY : src/Alien.o

# target to build an object file
src/Alien.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Alien.cpp.o
.PHONY : src/Alien.cpp.o

src/Alien.i: src/Alien.cpp.i
.PHONY : src/Alien.i

# target to preprocess a source file
src/Alien.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Alien.cpp.i
.PHONY : src/Alien.cpp.i

src/Alien.s: src/Alien.cpp.s
.PHONY : src/Alien.s

# target to generate assembly for a file
src/Alien.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Alien.cpp.s
.PHONY : src/Alien.cpp.s

src/AnchorPoint.o: src/AnchorPoint.cpp.o
.PHONY : src/AnchorPoint.o

# target to build an object file
src/AnchorPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/AnchorPoint.cpp.o
.PHONY : src/AnchorPoint.cpp.o

src/AnchorPoint.i: src/AnchorPoint.cpp.i
.PHONY : src/AnchorPoint.i

# target to preprocess a source file
src/AnchorPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/AnchorPoint.cpp.i
.PHONY : src/AnchorPoint.cpp.i

src/AnchorPoint.s: src/AnchorPoint.cpp.s
.PHONY : src/AnchorPoint.s

# target to generate assembly for a file
src/AnchorPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/AnchorPoint.cpp.s
.PHONY : src/AnchorPoint.cpp.s

src/GameOverState.o: src/GameOverState.cpp.o
.PHONY : src/GameOverState.o

# target to build an object file
src/GameOverState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/GameOverState.cpp.o
.PHONY : src/GameOverState.cpp.o

src/GameOverState.i: src/GameOverState.cpp.i
.PHONY : src/GameOverState.i

# target to preprocess a source file
src/GameOverState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/GameOverState.cpp.i
.PHONY : src/GameOverState.cpp.i

src/GameOverState.s: src/GameOverState.cpp.s
.PHONY : src/GameOverState.s

# target to generate assembly for a file
src/GameOverState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/GameOverState.cpp.s
.PHONY : src/GameOverState.cpp.s

src/MenuState.o: src/MenuState.cpp.o
.PHONY : src/MenuState.o

# target to build an object file
src/MenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/MenuState.cpp.o
.PHONY : src/MenuState.cpp.o

src/MenuState.i: src/MenuState.cpp.i
.PHONY : src/MenuState.i

# target to preprocess a source file
src/MenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/MenuState.cpp.i
.PHONY : src/MenuState.cpp.i

src/MenuState.s: src/MenuState.cpp.s
.PHONY : src/MenuState.s

# target to generate assembly for a file
src/MenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/MenuState.cpp.s
.PHONY : src/MenuState.cpp.s

src/PlayState.o: src/PlayState.cpp.o
.PHONY : src/PlayState.o

# target to build an object file
src/PlayState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/PlayState.cpp.o
.PHONY : src/PlayState.cpp.o

src/PlayState.i: src/PlayState.cpp.i
.PHONY : src/PlayState.i

# target to preprocess a source file
src/PlayState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/PlayState.cpp.i
.PHONY : src/PlayState.cpp.i

src/PlayState.s: src/PlayState.cpp.s
.PHONY : src/PlayState.s

# target to generate assembly for a file
src/PlayState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/PlayState.cpp.s
.PHONY : src/PlayState.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/StateManager.o: src/StateManager.cpp.o
.PHONY : src/StateManager.o

# target to build an object file
src/StateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/StateManager.cpp.o
.PHONY : src/StateManager.cpp.o

src/StateManager.i: src/StateManager.cpp.i
.PHONY : src/StateManager.i

# target to preprocess a source file
src/StateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/StateManager.cpp.i
.PHONY : src/StateManager.cpp.i

src/StateManager.s: src/StateManager.cpp.s
.PHONY : src/StateManager.s

# target to generate assembly for a file
src/StateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/StateManager.cpp.s
.PHONY : src/StateManager.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_program"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Alien.o"
	@echo "... src/Alien.i"
	@echo "... src/Alien.s"
	@echo "... src/AnchorPoint.o"
	@echo "... src/AnchorPoint.i"
	@echo "... src/AnchorPoint.s"
	@echo "... src/GameOverState.o"
	@echo "... src/GameOverState.i"
	@echo "... src/GameOverState.s"
	@echo "... src/MenuState.o"
	@echo "... src/MenuState.i"
	@echo "... src/MenuState.s"
	@echo "... src/PlayState.o"
	@echo "... src/PlayState.i"
	@echo "... src/PlayState.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/StateManager.o"
	@echo "... src/StateManager.i"
	@echo "... src/StateManager.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

